services:

  ### Workspace Utilities ##################################
  workspace:
    image: angaozhao/laravel-workspace:laravel10-1.0.0
    volumes:
      - /var/jenkins_home/workspace/{projectName}:/var/www:cached
      - /var/www/node_modules
    tty: true
    logging:
      options:
        max-file: "5"
        max-size: "10m"