services:
  ### Jenkins ###################################################
  jenkins:
    build: ./docker
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true"
    ports:
      - "50000:50000"
      - "8080:8080"
    privileged: true
    volumes:
      - /var/www/html:/var/www/html
      - ./jenkins_home:/var/jenkins_home
      - ./jenkins_data:/var/www/jenkins_data
      - /var/run/docker.sock:/var/run/docker.sock