version: '3'
services:
  jenkins:
    build: ./docker
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./certs:/certs/client
    ports:
      - "8080:8080"
      - "50000:50000"
    depends_on:
      - docker

  docker:
    image: docker:20.10-dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: "/certs"
    volumes:
      - "./certs:/certs/server"
      - ./jenkins_home:/var/jenkins_home
    ports:
      - "2376:2376"

volumes:
  docker-certs-client:
  docker-certs-server:
